FROM nginx:latest
# This will tell docker to pull the nginx image (based on linux)

# docker build -t tag1 .                ~ must be the same directory or ~~
# docker build -t tag1 -f Project_2/

# docker images                         ~ will show nginx in the list

# docker run -d -p 80:80 container-id   ~ access to port "80":80 is when someone visits the site and 80:"80" is the forwarding port

docker ps