---
  - name: Initialise Manager Node
    connection: local
    become: true
    roles:
    - docker
    - docker-swarm
    
  - name: Initialise Worker Stack
    hosts: stack
    become: true
    roles:
    - docker
    - docker-swarm-worker