---
  - name: Install Docker
    hosts: network
    become: true
    roles:
    - docker
    
  - name: Initialise Docker Swarm
    connection: local
    hosts: manager
    become: true
    roles:
    - docker-swarm
    
  - name: Add workers to Docker Swarm
    hosts: stack
    become: true
    roles:
    - docker-swarm-worker